channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- pip=25.1.1
- pip:
  - mlflow==2.4.1
  - scikit-learn==1.7.0
  - pandas==2.3.1
  - numpy==1.26.4
  - joblib==1.5.1
  - azureml-inference-server-http==0.8.4
name: azureml-compatible-env
