name: financial-behavior-insights
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11.12
  
  # ML and data science libraries (current environment versions)
  - scikit-learn=1.7.0
  - pandas=2.3.1
  - numpy=1.26.4
  - joblib=1.5.1
  - scipy=1.11.0
  
  # Visualization
  - matplotlib=3.7.0
  - seaborn=0.12.0
  
  # Jupyter and notebooks
  - jupyter=1.0.0
  - ipykernel=6.0.0
  
  # Pip dependencies (packages not available via conda)
  - pip=24.3.1
  - pip:
    # Azure ML and MLflow (current versions)
    - mlflow==2.22.1
    - azure-ai-ml==1.28.1
    - azureml-mlflow==1.57.0
    - azure-core>=1.24.0
    - azure-identity>=1.12.0
    - azure-keyvault-secrets>=4.6.0
    - azure-storage-blob>=12.14.0
    
    # Data pipeline
    - dvc[azure]==3.48.4
    - python-dotenv>=1.0.0
    
    # Web framework
    - flask>=2.3.0
    - pydantic>=2.0.0
    
    # Development and testing
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    
    # Utilities
    - requests>=2.31.0
    - pyyaml>=6.0.0
    - click>=8.0.0