version: '3.8'

# Azure App Service Optimized Docker Compose
# This configuration is optimized for Azure App Service deployment

services:
  # Main Application (Azure App Service)
  app:
    build:
      context: .
      dockerfile: Dockerfile.azure
    container_name: intelligent-document-analysis-azure
    environment:
      # Azure App Service Configuration
      - PORT=8000
      - WEBSITES_PORT=8000
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITES_CONTAINER_START_TIME_LIMIT=1800
      - PYTHONPATH=/app
      
      # Streamlit Configuration (Azure optimized)
      - STREAMLIT_SERVER_PORT=8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      
      # Database Configuration (Azure PostgreSQL)
      - DATABASE_URL=${DATABASE_URL}
      
      # Redis Configuration (Azure Cache for Redis)
      - REDIS_URL=${REDIS_URL}
      
      # Azure OpenAI Configuration
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2023-12-01-preview}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-gpt-4o}
      
      # Azure Document Intelligence Configuration
      - AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT=${AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT}
      - AZURE_DOCUMENT_INTELLIGENCE_API_KEY=${AZURE_DOCUMENT_INTELLIGENCE_API_KEY}
      
      # Azure Storage Configuration
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME:-documents}
      
      # Application Configuration
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      
      # Security
      - SECRET_KEY=${SECRET_KEY}
      
      # File Upload Configuration
      - MAX_FILE_SIZE_STANDARD=15728640  # 15MB
      - MAX_FILE_SIZE_LARGE=209715200    # 200MB
      - MAX_DOCUMENT_LENGTH=100000
      
      # AI Processing Configuration
      - MAX_TOKENS=4000
      - TEMPERATURE=0.3
      
      # Monitoring
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
    
    volumes:
      - azure_temp:/app/temp
      - azure_uploads:/app/uploads
      - azure_logs:/app/logs
    
    ports:
      - "8000:8000"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    # Azure-specific resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Local PostgreSQL for development/testing (not used in Azure)
  postgres-local:
    image: postgres:15-alpine
    container_name: document_analysis_db_local
    environment:
      POSTGRES_DB: document_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - local-dev

  # Local Redis for development/testing (not used in Azure)
  redis-local:
    image: redis:7-alpine
    container_name: document_analysis_redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    profiles:
      - local-dev

volumes:
  azure_temp:
    driver: local
  azure_uploads:
    driver: local
  azure_logs:
    driver: local
  postgres_data_local:
    driver: local
  redis_data_local:
    driver: local

networks:
  default:
    name: intelligent-document-analysis-azure
