apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligent-document-analysis
  labels:
    app: intelligent-document-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intelligent-document-analysis
  template:
    metadata:
      labels:
        app: intelligent-document-analysis
    spec:
      containers:
      - name: intelligent-document-analysis
        image: your-registry.azurecr.io/intelligent-document-analysis:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: WEBSITES_PORT
          value: "8000"
        - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
          value: "false"
        - name: WEBSITES_CONTAINER_START_TIME_LIMIT
          value: "1800"
        - name: PYTHONPATH
          value: "/app"
        - name: STREAMLIT_SERVER_PORT
          value: "8000"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_SERVER_ENABLE_CORS
          value: "false"
        - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
          value: "false"
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: azure-openai-endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: azure-openai-api-key
        - name: AZURE_OPENAI_DEPLOYMENT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: azure-openai-deployment-name
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: azure-storage-account-name
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: azure-storage-account-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: temp-storage
          mountPath: /app/temp
        - name: uploads-storage
          mountPath: /app/uploads
        - name: logs-storage
          mountPath: /app/logs
      volumes:
      - name: temp-storage
        emptyDir: {}
      - name: uploads-storage
        emptyDir: {}
      - name: logs-storage
        emptyDir: {}
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: intelligent-document-analysis-service
  labels:
    app: intelligent-document-analysis
spec:
  selector:
    app: intelligent-document-analysis
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
data:
  azure-openai-endpoint: <base64-encoded-endpoint>
  azure-openai-api-key: <base64-encoded-api-key>
  azure-openai-deployment-name: <base64-encoded-deployment-name>
  azure-storage-account-name: <base64-encoded-storage-account-name>
  azure-storage-account-key: <base64-encoded-storage-account-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>
