# Azure Monitoring Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    scrape_configs:
      - job_name: 'intelligent-document-analysis'
        static_configs:
          - targets: ['localhost:8000']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      - job_name: 'azure-app-service'
        static_configs:
          - targets: ['localhost:9090']
        scrape_interval: 60s

  alert_rules.yml: |
    groups:
      - name: intelligent-document-analysis
        rules:
          - alert: HighMemoryUsage
            expr: memory_usage_percent > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Memory usage is above 80% for more than 5 minutes"
          
          - alert: HighCPUUsage
            expr: cpu_usage_percent > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% for more than 5 minutes"
          
          - alert: ApplicationDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Application is down"
              description: "The application is not responding"
