name: CI/CD Pipeline for Loan Predictor App

on:
  push:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies
        run: |
          pip install pytest requests

      - name: Build Docker image
        run: docker build -t loan-predictor-app .

      - name: Run Docker container for tests
        run: |
          docker run -d --name loan-predictor-api -p 8000:8000 loan-predictor-app
          sleep 5  # give FastAPI some time to start

      - name: Run pytest
        run: pytest tests/

      - name: Log in to DockerHub (optional if secrets exist)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_PASSWORD" ]; then
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          else
            echo "🔒 Docker credentials not found. Skipping login."
          fi

      - name: Cleanup container
        if: always()
        run: |
          docker stop loan-predictor-api
          docker rm loan-predictor-api
