name: Portfolio CI/CD

on:
  push:
    branches: [main, dev]
    paths:
      - 'phase-4-portfolio-resume/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'phase-4-portfolio-resume/**'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phase-4-portfolio-resume/portfolio-site

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: phase-4-portfolio-resume/portfolio-site/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run tests
        run: npm run test:coverage

      - name: Build project
        run: npm run build

  deploy:
    needs: quality-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: phase-4-portfolio-resume/portfolio-site

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: phase-4-portfolio-resume/portfolio-site/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 